apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: welcome-php
  name: welcome-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-php
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: welcome-php
    spec:
      containers:
      - image: quay.io/redhatworkshops/welcome-php:latest
        name: welcome-php
        resources: {}
---        
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  selector:
    iapp.kubernetes.io/name: welcome-php
  ports:
    - protocol: TCP
      port: 899
      targetPort: 9376
---
